### ISSUE TITLE
about the api endpoint of ARWU

### ISSUE THREAD

**Issue by zhoudaxia233** [yym68686/uniRank#1]
你好，首先很感谢你的代码。我想请教一下你是怎么得到软科的api的地址的呢？我F12研究半天也没找到。。。

**Comment by yym68686** [comment]
22 年跟 23 年 api 不一样

22年的寻找方法在 [README](https://github.com/yym68686/uniRank#2022-%E8%BD%AF%E7%A7%91%E4%B8%AD%E5%9B%BD%E5%A4%A7%E5%AD%A6%E4%B8%93%E4%B8%9A%E6%8E%92%E5%90%8D-bcsr) 这里面。

23年的 api 直接下载 payload.js 按照 [2023-bcur](https://github.com/yym68686/uniRank/tree/main/rk/2023-bcur) 的提取方法。
